"""Golden de-tokeniser vectors from the genuine BBC BASIC II ROM.

Generated by scripts/gen_rom_detok_golden.py from basictool's 6502
emulation of the BASIC II ROM and committed as static data: the ROM's
LIST output is the authority for what de-tokenising must produce (the
expected text is rebuilt in our plain line-number style from the ROM's
LIST bodies). basictool is NOT a test dependency.
"""

import pytest
from oaknut.basic import detokenise

# (tokenised program bytes, expected de-tokenised text).
_GOLDEN = [
    (b'\r\x00\n\x16 \xf1 "Hello, world!"\r\xff', '10 PRINT "Hello, world!"\n'),
    (b'\r\x00\n\x0b \xe5 \x8dDd@\r\xff', '10 GOTO 100\n'),
    (b'\r\x00\n\r \xe4 \x8ddH@:\xf8\r\xff', '10 GOSUB 200:RETURN\n'),
    (b'\r\x00\n\x19 \xee X \xe5 \x8dTJ@,\x8dTT@,\x8dT^@\r\xff', '10 ON X GOTO 10,20,30\n'),
    (b'\r\x00\n\x18 \xe7 A=1 \x8c \x8dTr@ \x8b \x8dT|@\r\xff', '10 IF A=1 THEN 50 ELSE 60\n'),
    (b'\r\x00\n\x11 \xf7 \x8dDd@:\xf3 A,B\r\xff', '10 RESTORE 100:READ A,B\n'),
    (b'\r\x00\n\x17 \xe3 I=1 \xb8 10 \x88 2:\xed I\r\xff', '10 FOR I=1 TO 10 STEP 2:NEXT I\n'),
    (b'\r\x00\n\x0c \xf5:\xfd X>5\r\xff', '10 REPEAT:UNTIL X>5\n'),
    (b'\r\x00\n\x0c \xd0=&2000\r\xff', '10 PAGE=&2000\n'),
    (b'\r\x00\n\x08 X=\x90\r\xff', '10 X=PAGE\n'),
    (b'\r\x00\n\n \xcf#3=0\r\xff', '10 PTR#3=0\n'),
    (b'\r\x00\n\x0c \xd1=0:X=\x91\r\xff', '10 TIME=0:X=TIME\n'),
    (b'\r\x00\n\x10 \xd3=&7C00:\xd2=\x90\r\xff', '10 HIMEM=&7C00:LOMEM=PAGE\n'),
    (b'\r\x00\n\x15 A$=\xbd(34)+"quote"\r\xff', '10 A$=CHR$(34)+"quote"\n'),
    (b'\r\x00\n\x1d \xf1 "GOTO 10 is text here"\r\xff', '10 PRINT "GOTO 10 is text here"\n'),
    (b'\r\x00\n\x16 X=&FF+&1A2B \x80 &F0\r\xff', '10 X=&FF+&1A2B AND &F0\n'),
    (b'\r\x00\n\x10 Y=1.5E3+.25\r\xff', '10 Y=1.5E3+.25\n'),
    (b'\r\x00\n$ \xf4 this REM has PRINT GOTO in it\r\xff', '10 REM this REM has PRINT GOTO in it\n'),
    (b'\r\x00\n\x18 \xdc 1,2,PRINT,3,hello\r\xff', '10 DATA 1,2,PRINT,3,hello\n'),
    (b'\r\x00\n\t *CAT\r\xff', '10 *CAT\n'),
    (b'\r\x00\n\x14 \xef 23,255;0;0;0;\r\xff', '10 VDU 23,255;0;0;0;\n'),
    (b'\r\x00\n\x13 \xf2draw(x%,y%):\xe1\r\xff', '10 PROCdraw(x%,y%):ENDPROC\n'),
    (b'\r\x00\n\x11 \xdd \xa4sq(x)=x*x\r\xff', '10 DEF FNsq(x)=x*x\n'),
    (b'\r\x00\n\x11 L%=\xa9(A$)+\xb1-\x9c\r\xff', '10 L%=LEN(A$)+POS-COUNT\n'),
    (b'\r\x00\n\x12 X=\xa8(\xb3(1)*6)+1\r\xff', '10 X=INT(RND(1)*6)+1\n'),
    (b'\r\x00\n\n \xf1~&AB\r\xff', '10 PRINT~&AB\n'),
    (b'\r\x00\n\x14 @%=&90A:\xf1 \x8a5);X\r\xff', '10 @%=&90A:PRINT TAB(5);X\n'),
    (b'\r\x00\n\x12 \xfb 129:\xe6 0,1:\xdb\r\xff', '10 COLOUR 129:GCOL 0,1:CLS\n'),
    (b"\r\x00\n\x10 \xeb 7:\xf1'\x8a10)'\r\xff", "10 MODE 7:PRINT'TAB(10)'\n"),
    (b'\r\x00\n\x17 ?(addr%+1)=base%?2\r\xff', '10 ?(addr%+1)=base%?2\n'),
]


@pytest.mark.parametrize(("program", "expected"), _GOLDEN, ids=range(len(_GOLDEN)))
def test_detokenises_like_the_basic_ii_rom(program, expected):
    assert detokenise(program) == expected
