"""Golden tokeniser vectors from the genuine BBC BASIC II ROM.

Generated by scripts (basictool's 6502 emulation of the BASIC II ROM)
and committed as static data: the ROM is the authority for what the
tokeniser must produce, and this test holds it to that. basictool is
NOT a test dependency — regenerate with scripts/gen_rom_golden.py if the
vector set changes.
"""

import pytest
from oaknut.basic import tokenise

# (source after the line number, tokenised body the ROM produces).
_GOLDEN = [
    ('PRINT "Hi"', b' \xf1 "Hi"'),
    ('END', b' \xe0'),
    ('GOTO 100', b' \xe5 \x8dDd@'),
    ('FOR I=1 TO 10 STEP 2', b' \xe3 I=1 \xb8 10 \x88 2'),
    ('NEXT I', b' \xed I'),
    ('REPEAT', b' \xf5'),
    ('UNTIL X>5', b' \xfd X>5'),
    ('IF A=1 THEN PRINT A', b' \xe7 A=1 \x8c \xf1 A'),
    ('X=INT(RND(1)*6)+1', b' X=\xa8(\xb3(1)*6)+1'),
    ('PROCdraw(x%,y%)', b' \xf2draw(x%,y%)'),
    ('DEF PROCgbpb(A$,T%)', b' \xdd \xf2gbpb(A$,T%)'),
    ('DEF FNsq(x)=x*x', b' \xdd \xa4sq(x)=x*x'),
    ('=FNsq(3)', b' =\xa4sq(3)'),
    ('P.', b' \xf1'),
    ('PR.', b' \xf1'),
    ('PRO.', b' \xf2'),
    ('F.', b' \xe3'),
    ('N.', b' \xed'),
    ('G.100', b' \xe5\x8dDd@'),
    ('REP.', b' \xf5'),
    ('AND0', b' \x80\x8dT@@'),
    ('TO1', b' \xb8\x8dTA@'),
    ('PRINT1', b' \xf11'),
    ('DIV9', b' \x81\x8dTI@'),
    ('SIN1', b' \xb5\x8dTA@'),
    ('TAB(1', b' \x8a\x8dTA@'),
    ('X=2', b' X=2'),
    ('5', b' \x8dTE@'),
    ('GOTO0', b' \xe5\x8dT@@'),
    ('GOTO1', b' \xe5\x8dTA@'),
    ('GOTO 10', b' \xe5 \x8dTJ@'),
    ('GOTO 32767', b' \xe5 \x8d`\x7f\x7f'),
    ('GOSUB 100', b' \xe4 \x8dDd@'),
    ('RESTORE 100,200', b' \xf7 \x8dDd@,\x8ddH@'),
    ('ON X GOTO 10,20,30', b' \xee X \xe5 \x8dTJ@,\x8dTT@,\x8dT^@'),
    ('IF A THEN 100 ELSE 200', b' \xe7 A \x8c \x8dDd@ \x8b \x8ddH@'),
    ('GOTO X', b' \xe5 X'),
    ('GOTO -5', b' \xe5 -5'),
    ('RESTORE', b' \xf7'),
    ('TRACE 500', b' \xfc \x8ddtA'),
    ('RENUMBER 100,10', b' \xcc \x8dDd@,\x8dTJ@'),
    ('PAGE=&2000', b' \xd0=&2000'),
    ('X=PAGE', b' X=\x90'),
    ('PRINT PAGE', b' \xf1 \x90'),
    ('TIME=0', b' \xd1=0'),
    ('X=TIME', b' X=\x91'),
    ('PTR#3=0', b' \xcf#3=0'),
    ('X=PTR#3', b' X=\x8f#3'),
    ('HIMEM=&7C00', b' \xd3=&7C00'),
    ('LOMEM=PAGE', b' \xd2=\x90'),
    ('? ERR PAGE', b' ? \x9f \x90'),
    ('GET$;,PTR', b' \xbe;,\x8f'),
    ('INSTR(A$,B$) PTR', b' \xa7A$,B$) \x8f'),
    ('OPENOUT LOMEM', b' \xae \xd2'),
    ('SQR RAD PTR', b' \xb6 \xb2 \xcf'),
    ('RND * SQR ENDPROC', b' \xb3 * SQR ENDPROC'),
    ('A$="he""llo"', b' A$="he""llo"'),
    ('PRINT "GOTO 10"', b' \xf1 "GOTO 10"'),
    ('X=&FF+&1A2B', b' X=&FF+&1A2B'),
    ('Y=1.5E3+.25', b' Y=1.5E3+.25'),
    ('PRINT "unterminated GOTO', b' \xf1 "unterminated GOTO'),
    ('REM this has PRINT GOTO 10', b' \xf4 this has PRINT GOTO 10'),
    ('DATA 1,2,PRINT,3:X=4', b' \xdc 1,2,PRINT,3:X=4'),
    ('*CAT', b' *CAT'),
    ('*FX 21,0', b' *FX 21,0'),
    ('X=3*4', b' X=3*4'),
    ('PRINT~&FF', b' \xf1~&FF'),
    ('VDU 26,12;0;', b' \xef 26,12;0;'),
    ('TIMER', b' TIMER'),
    ('TRUEELSE', b' TRUEELSE'),
    ('GDIV40', b' GDIV40'),
    ('TOTAL', b' \xb8TAL'),
    ('DIVMOD', b' \x81\x83'),
    ('TRUE+', b' \xb9+'),
    ('text%?p%=ASC(MID$(A$,i%,1))', b' text%?p%=\x97(\xc1A$,i%,1))'),
    ('?(a%+1)=&FF', b' ?(a%+1)=&FF'),
    ('A=1:B=2:PRINT A,B', b' A=1:B=2:\xf1 A,B'),
    ('COLOUR 129:CLS', b' \xfb 129:\xdb'),
    ('MODE 7:VDU 23', b' \xeb 7:\xef 23'),
]


@pytest.mark.parametrize(("source", "expected_body"), _GOLDEN, ids=[v[0] for v in _GOLDEN])
def test_tokenises_like_the_basic_ii_rom(source, expected_body):
    program = tokenise("10 " + source)
    assert program[4 : program[3]] == expected_body
