"""Generate a static golden de-tokeniser test from the BASIC II ROM.

Build-time only: tokenises each source with basictool -2, asks the ROM to
LIST it back, and records (tokenised program, expected text) — with the
text rebuilt in our plain line-number style from the ROM's LIST bodies, so
it is the ROM's own de-tokenisation. The committed test runs our codec
against the static data; basictool is not a test dependency."""

from __future__ import annotations

import os
import subprocess
import tempfile
from pathlib import Path

BT = os.environ.get("BASICTOOL", "/Users/rjs/Code/basictool/basictool")
OUT = Path("/Users/rjs/Code/oaknut/packages/oaknut-basic/tests/test_rom_golden_detokenise.py")

# Source programs exercising the de-tokeniser: token expansion, &8D
# line-number references, pseudo-variable assignment vs function forms,
# strings, hex, multi-statement lines, REM/DATA.
INPUTS = [
    'PRINT "Hello, world!"',
    "GOTO 100",
    "GOSUB 200:RETURN",
    "ON X GOTO 10,20,30",
    "IF A=1 THEN 50 ELSE 60",
    "RESTORE 100:READ A,B",
    "FOR I=1 TO 10 STEP 2:NEXT I",
    "REPEAT:UNTIL X>5",
    "PAGE=&2000",
    "X=PAGE",
    "PTR#3=0",
    "TIME=0:X=TIME",
    "HIMEM=&7C00:LOMEM=PAGE",
    'A$=CHR$(34)+"quote"',
    'PRINT "GOTO 10 is text here"',
    "X=&FF+&1A2B AND &F0",
    "Y=1.5E3+.25",
    "REM this REM has PRINT GOTO in it",
    "DATA 1,2,PRINT,3,hello",
    "*CAT",
    "VDU 23,255;0;0;0;",
    "PROCdraw(x%,y%):ENDPROC",
    "DEF FNsq(x)=x*x",
    "L%=LEN(A$)+POS-COUNT",
    "X=INT(RND(1)*6)+1",
    "P.~&AB",
    "@%=&90A:PRINT TAB(5);X",
    "COLOUR 129:GCOL 0,1:CLS",
    "MODE 7:PRINT'TAB(10)'",
    "?(addr%+1)=base%?2",
]


def line_numbers(p: bytes) -> list[int]:
    nums, i = [], 0
    while i < len(p) and p[i] == 0x0D and p[i + 1] != 0xFF:
        nums.append((p[i + 1] << 8) | p[i + 2])
        i += p[i + 3]
    return nums


def rom_bodies(text: str, nums: list[int]) -> list[str]:
    lines = [ln for ln in text.split("\n") if ln != ""]
    out = []
    for ln, num in zip(lines, nums):
        s = ln.lstrip(" ")
        out.append(s[len(str(num)) :])
    return out


def run(args: list[str], data: bytes | None = None) -> bytes:
    with tempfile.NamedTemporaryFile() as f:
        if data is not None:
            Path(f.name).write_bytes(data)
        r = subprocess.run([BT, *args, f.name, "-"], capture_output=True)
        if r.returncode != 0:
            raise SystemExit(f"basictool failed: {r.stderr.decode(errors='replace')}")
        return r.stdout


vectors = []
for s in INPUTS:
    program = run(["-2", "-t", "--output-binary"], f"10 {s}\n".encode("latin-1"))
    listing = run(["-2", "--input-tokenised"], program).decode("latin-1")
    nums = line_numbers(program)
    expected = "".join(f"{num}{body}\n" for num, body in zip(nums, rom_bodies(listing, nums)))
    vectors.append((program, expected))

lines = [
    '"""Golden de-tokeniser vectors from the genuine BBC BASIC II ROM.',
    "",
    "Generated by scripts/gen_rom_detok_golden.py from basictool's 6502",
    "emulation of the BASIC II ROM and committed as static data: the ROM's",
    "LIST output is the authority for what de-tokenising must produce (the",
    "expected text is rebuilt in our plain line-number style from the ROM's",
    "LIST bodies). basictool is NOT a test dependency.",
    '"""',
    "",
    "import pytest",
    "from oaknut.basic import detokenise",
    "",
    "# (tokenised program bytes, expected de-tokenised text).",
    "_GOLDEN = [",
]
for program, expected in vectors:
    lines.append(f"    ({program!r}, {expected!r}),")
lines += [
    "]",
    "",
    "",
    '@pytest.mark.parametrize(("program", "expected"), _GOLDEN, ids=range(len(_GOLDEN)))',
    "def test_detokenises_like_the_basic_ii_rom(program, expected):",
    "    assert detokenise(program) == expected",
    "",
]
OUT.write_text("\n".join(lines))
print(f"wrote {len(vectors)} de-tokenise golden vectors to {OUT}")
